"""baseline schema

Revision ID: 71d18a88bb0a
Revises: 
Create Date: 2026-06-28 03:35:11.937196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d18a88bb0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('national_id_number', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_front', sa.Text(), nullable=False),
    sa.Column('document_back', sa.Text(), nullable=True),
    sa.Column('selfie_image', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('api_user', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('target_environment', sa.String(length=50), nullable=False),
    sa.Column('callback_host', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mtn_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mtn_credentials_api_user'), ['api_user'], unique=True)
        batch_op.create_index(batch_op.f('ix_mtn_credentials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtn_credentials_product_type'), ['product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtn_credentials_target_environment'), ['target_environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtn_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_network', sa.String(length=20), nullable=True),
    sa.Column('receiver_network', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('callback_payload', sa.JSON(), nullable=True),
    sa.Column('wallet_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference_id'), ['reference_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_processed'), ['wallet_processed'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_processed'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_provider'))
        batch_op.drop_index(batch_op.f('ix_transactions_currency'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('mtn_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtn_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_mtn_credentials_target_environment'))
        batch_op.drop_index(batch_op.f('ix_mtn_credentials_product_type'))
        batch_op.drop_index(batch_op.f('ix_mtn_credentials_is_active'))
        batch_op.drop_index(batch_op.f('ix_mtn_credentials_api_user'))

    op.drop_table('mtn_credentials')
    op.drop_table('kyc')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
