"""add residential_address to kyc

Revision ID: 79a58987b979
Revises: 3c0978ba6583
Create Date: 2026-07-01 00:38:19.373383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a58987b979'
down_revision = '3c0978ba6583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residential_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc', schema=None) as batch_op:
        batch_op.drop_column('residential_address')

    # ### end Alembic commands ###
